repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args:
          - --maxkb=2500
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args:
          - autofix
          - --indent=4
          - --no-ensure-ascii
          - --no-sort-keys
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - "--profile"
          - "black"
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - "--line-length"
          - "90"
          - "--skip-string-normalization"
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1 # Ensure this is a valid tag
    hooks:
      - id: flake8
        args:
          - "--ignore"
          - "E501,W503,E302"
  - repo: https://github.com/PyCQA/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        args:
          - "--errors-only"
          - "--disable=E0401"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.960
    hooks:
      - id: mypy
        args:
          - --strict
          - --ignore-missing-imports
          - --allow-subclassing-any
          - --allow-untyped-decorators
          - --no-warn-return-any
        additional_dependencies: [types-all]
